chore(docs): Relocate documentation files
This commit relocates documentation files into a new `context/modules` directory.

- `TECHNICAL_REVIEW.md` is now located at `context/modules/TECHNICAL_REVIEW.md`.
- `MUST READ INFORMATION READNOW.MD` is now located at `context/modules/MUST READ INFORMATION READNOW.MD`.

Gradle cache and lock files have been updated as a result of these file movements.> Task :colorblendr:mergeExtDexDebugAndroidTest FAILED
                                                                                  AGPBI: {"kind":"error","text":"Cannot fit requested classes in a single dex file (# methods: 91958 > 65536)","sources":[{}],"tool":"D8"}
                                                                                  com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
                                                                                  The number of method references in a .dex file cannot exceed 64K.
                                                                                  Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
                                                                                  	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:230)
                                                                                  	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:218)
                                                                                  	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:935)
                                                                                  	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:884)
                                                                                  	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
                                                                                  	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:68)
                                                                                  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:64)
                                                                                  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:61)
                                                                                  	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
                                                                                  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:61)
                                                                                  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
                                                                                  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
                                                                                  	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
                                                                                  	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
                                                                                  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:58)
                                                                                  	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:176)
                                                                                  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
                                                                                  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:194)
                                                                                  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:127)
                                                                                  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:169)
                                                                                  	at org.gradle.internal.Factories$1.create(Factories.java:33)
                                                                                  	at org.gradle.internal.work.DefaultWorkerLeaseService.lambda$withLocksAcquired$0(DefaultWorkerLeaseService.java:269)
                                                                                  	at org.gradle.internal.work.ResourceLockStatistics$1.measure(ResourceLockStatistics.java:42)
                                                                                  	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocksAcquired(DefaultWorkerLeaseService.java:267)
                                                                                  	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:259)
                                                                                  	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:127)
                                                                                  	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:132)
                                                                                  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
                                                                                  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:133)
                                                                                  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:545)
                                                                                  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
                                                                                  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
                                                                                  	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
                                                                                  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
                                                                                  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
                                                                                  	at java.base/java.lang.Thread.run(Thread.java:1474)
                                                                                  Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
                                                                                  	at Version.fakeStackEntry(Version_9.0.17-dev.java:0)
                                                                                  	at com.android.tools.r8.r0.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:1)
                                                                                  	at com.android.tools.r8.internal.fu0.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:81)
                                                                                  	at com.android.tools.r8.internal.fu0.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:32)
                                                                                  	at com.android.tools.r8.internal.fu0.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:31)
                                                                                  	at com.android.tools.r8.internal.fu0.b(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:2)
                                                                                  	at com.android.tools.r8.D8.run(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:11)
                                                                                  	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:216)
                                                                                  	... 40 more
                                                                                  Caused by: com.android.tools.r8.internal.j: Cannot fit requested classes in a single dex file (# methods: 91958 > 65536)
                                                                                  Cannot fit requested classes in a single dex file (# methods: 91958 > 65536)
                                                                                  Explain with AI

                                                                                  	at com.android.tools.r8.internal.dk3.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:21)
                                                                                  	at com.android.tools.r8.dex.h1.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:29)
                                                                                  	at com.android.tools.r8.dex.k.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:73)
                                                                                  	at com.android.tools.r8.dex.k.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:183)
                                                                                  	at com.android.tools.r8.D8.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:113)
                                                                                  	at com.android.tools.r8.D8.d(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:151)
                                                                                  	at com.android.tools.r8.D8.b(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:1)
                                                                                  	at com.android.tools.r8.internal.fu0.a(R8_9.0.17-dev_294f1751ac8ba4c4baf402cc1de01a4a3f00740d3de07fa6a9d9bc958171dda9:28)
                                                                                  	... 43 more

                                                                                  Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
                                                                                  Explain with AI

                                                                                  Caused by: com.android.tools.r8.internal.j: Cannot fit requested classes in a single dex file (# methods: 91958 > 65536)
                                                                                  Explain with AI

                                                                                  Execution failed for task ':colorblendr:mergeExtDexDebugAndroidTest'.
                                                                                  > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
                                                                                     > There was a failure while executing work items
                                                                                        > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
                                                                                           > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
                                                                                             The number of method references in a .dex file cannot exceed 64K.
                                                                                             Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

                                                                                  * Try:
                                                                                  > Run with --stacktrace option to get the stack trace.
                                                                                  > Run with --info or --debug option to get more log output.
                                                                                  > Run with --scan to generate a Build Scan (powered by Develocity).
                                                                                  > Get more help at https://help.gradle.org.
                                                                                  Explain with AI